#!/usr/bin/env node
/**
 * Embed `bin/jmp2` into `src/cli.js` so the Worker can serve it at /cli.
 *
 * The direction of truth is bin/jmp2 -> src/cli.js: the shell script stays a
 * real, editable, executable file, and this only mirrors it into the bundle.
 * `test/cli.test.js` fails if the two drift, so regenerating is never optional.
 *
 *   npm run build:cli
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = readFileSync(join(root, 'bin/jmp2'), 'utf8');

// Escape only what a template literal treats specially.
const escaped = source
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

// The host baked into the script. The Worker swaps this for its own
// ROOT_DOMAIN when serving /cli, so a client installed from a fork points at
// that fork instead of at wherever the file happened to be built.
const host = /JMP2_API:-https:\/\/([^}"]+)/.exec(source)?.[1];
if (!host) throw new Error('bin/jmp2 no longer contains a recognizable default API host');

const out = `// Generated by scripts/build-cli.mjs from bin/jmp2 — do not edit by hand.
// Run \`npm run build:cli\` after changing the CLI; a test enforces they match.

export const DEFAULT_API_HOST = ${JSON.stringify(host)};

export const CLI_SOURCE = \`${escaped}\`;
`;

writeFileSync(join(root, 'src/cli.js'), out);
console.log(`src/cli.js written from bin/jmp2 (${Buffer.byteLength(source)} bytes)`);
